-- =============================================================================
-- lua/nsmbds/state.lua
-- Shared runtime state objects and global context for NSMB DS Archipelago
-- =============================================================================

local M = {}

M.notification_state = {
    sys = {
        magic_1 = 0x02002FED,
        magic_2 = 0x02002FEE,
        sequence = 0x02002FEF,
        kind = 0x02002FF0,
        detail = 0x02002FF1,
        acknowledged = 0x02002FF2,
    },
    addr = {},
    magic_1 = 0x4E,
    magic_2 = 0x53,
    kind = {
        time_capsule = 0x01,
        starman_lite = 0x02,
        trap_shield = 0x03,
        care_package = 0x04,
        life_insurance = 0x05,
        trap_blocked = 0x06,
        starman_buff = 0x07,
        goal_complete = 0x08,
        item_received = 0x09,
    },
    queue = {},
    active = nil,
    popup_disabled = false,
    remaining_frames = 0,
    default_duration_frames = 100,
    goal_duration_frames = 900,
    duration_frames = 100,
    max_queue_size = 64,
    protection_hud_was_ready = false,
    ready_wait_frames = 0,
    ready_warning_printed = false,
    snapshot = nil,
    snapshot_age = 3,
}

M.input_trap_state = {
    auto_direction = 1,
    sticky_direction = 0,
    sticky_frames = 0,
    sticky_last_frame = -1,
    sticky_duration = 36,
    no_turnaround_direction = 0,
    heavy_gravity_boost = 512,
    heavy_max_fall_speed = 22528,
    camera_direction = 1,
    camera_sway_period = 75,
    camera_drift_pulse_period = 12,
    camera_drift_pulse_frames = 6,
    camera_drift_ramp_frames = 48,
    boo_reverse_frames = 54,
    boo_cycle_frames = 180,
    im_stuck_frames = 180,
    im_stuck_player = nil,
    im_stuck_x = nil,
    im_stuck_y = nil,
    spotlight_frames = 600,
    action_damage_can_kill = true,
    action_damage_cooldown = 45,
    last_action_damage_frame = -1000,
    active_player = nil,
    player_was_moving_up = false,
    crazy_pixels_suspended = true,
    crazy_pixels_original_mosaic = {},
    crazy_pixels_original_bg = {},
    tint_index = 1,
    tint_colors = {
        0xD8FF3030,
        0xD830D060,
        0xD84060FF,
        0xD8D050D0,
        0xD8D09030,
    },
    original_rotation = nil,
}

M.context = {
    is_initialized = false,
    active_mode = "none",
    trap_remaining_frames = 0,
    trap_total_frames = 0,
    red_coin_peak_latched = { false, false },
    pending_red_coin_completion = nil,
    native_tile_changes = {},
    native_block_hits = {},
    native_tile_change_write_index = 1,
    native_block_hit_write_index = 1,
    ground_pound_hook_armed_frames = 0,
    ground_pound_down_held = false,
    change_tile_execute_hook_initialized = false,
    change_tile_execute_hook_attempted = false,
    hit_block_execute_hook_initialized = false,
    hit_block_execute_hook_attempted = false,
    red_coin_write_hook_initialized = false,
    input_filter_hooks_initialized = false,
    input_filter_hooks_attempted = false,
    life_insurance_write_guard = false,
    last_observed_lives = nil,
    last_drawn_shield_count = nil,
    last_drawn_insurance_count = nil,
    previous_frame_had_player = false,
    cached_player_object = nil,
    last_observer_frame = nil,
}

return M
